apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator-deployment
spec:
  selector:
    matchLabels:
      app: loadgen-cluster-sm
  replicas: 4
  template:
    metadata:
      labels:
        app: loadgen-cluster-sm
    spec:
      containers:
      - name: loadgenerator
        image: neotys/neoload-loadgenerator:6.5.1
        ports:
        - containerPort: 7100
