# kubectl get deployment ctrl-d487f15c-yzmpw -o yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-04-22T16:38:45Z"
  generation: 1
  labels:
    app: ctrl
    scope: d487f15c-7633-4789-9b87-bed8c05a08d2
    zone: yzmpw
  name: ctrl-d487f15c-yzmpw
  namespace: neoload
  resourceVersion: "3339"
  selfLink: /apis/extensions/v1beta1/namespaces/neoload/deployments/ctrl-d487f15c-yzmpw
  uid: 2dd99093-41a9-4eef-995b-093d5490ef6a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ctrl
      scope: d487f15c-7633-4789-9b87-bed8c05a08d2
      stackid: d487f15c-7633-4789-9b87-bed8c05a08d2yzmpw
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ctrl
        scope: d487f15c-7633-4789-9b87-bed8c05a08d2
        stackid: d487f15c-7633-4789-9b87-bed8c05a08d2yzmpw
    spec:
      containers:
      - env:
        - name: MODE
          value: Managed
        - name: NEOLOADWEB_URL
          value: https://neoload-api.saas.neotys.com
        - name: NEOLOADWEB_TOKEN
          value: [api_token_dynamically_set_by_runtime]
        - name: ZONE
          value: [the_zone_code]
        - name: AGENT_START_LOCKED_FOR
          value: d487f15c-7633-4789-9b87-bed8c05a08d2
        - name: AGENT_START_RESERVED
          value: "false"
        - name: CONTROLLER_XMX
          value: -Xmx2400m
        image: neotys/neoload-controller:latest
        imagePullPolicy: Always
        name: ctrl
        ports:
        - containerPort: 7100
          protocol: TCP
        resources:
          limits:
            cpu: 2500m
            memory: 3750M
          requests:
            cpu: 1800m
            memory: 2700M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - {}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2020-04-22T16:38:45Z"
    lastUpdateTime: "2020-04-22T16:38:45Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2020-04-22T16:38:45Z"
    lastUpdateTime: "2020-04-22T16:38:45Z"
    message: ReplicaSet "ctrl-d487f15c-yzmpw-9544d548f" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
